<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>ToolShare.Notifications</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ToolShare.Notifications.Domain.Shared\ToolShare.Notifications.Domain.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.Ddd.Application.Contracts" Version="10.6.0" />
    <PackageReference Include="Volo.Abp.Authorization" Version="10.6.0" />
  </ItemGroup>

</Project>
